sudo: required
services:
  - docker

before_install:
  - docker build -t devsuri/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run devsuri/react-test npm run test -- --coverage

after_success:
  - docker build -t "$DOCKER_USERNAME"/multi-client ./client
  - docker build -t "$DOCKER_USERNAME"/multi-nginx ./nginx
  - docker build -t "$DOCKER_USERNAME"/multi-server ./server
  - docker build -t "$DOCKER_USERNAME"/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME"/multi-client:latest
  - docker push "$DOCKER_USERNAME"/multi-nginx:latest
  - docker push "$DOCKER_USERNAME"/multi-server:latest
  - docker push "$DOCKER_USERNAME"/multi-worker:latest