sudo: required
services:
  - docker

before_install:
  - docker build -t devsuri/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run devsuri/react-test npm run test -- --coverage

after_success:
  - docker build -t devsuri/multi-client ./client
  - docker build -t devsuri/multi-nginx ./nginx
  - docker build -t devsuri/multi-server ./server
  - docker build -t devsuri/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push devsuri/multi-client
  - docker push devsuri/multi-nginx
  - docker push devsuri/multi-server
  - docker push devsuri/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region:
#  app:          #from elasticbeanstalk
#  env:          #from elasticbeanstalk
#  bucket_name:        #from S3 created bydefault for elasticbeanstalk app
#  bucket_path:
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECRET_KEY
